### ISSUE TITLE
Error when running service - Configuration throwing IsNullException

### ISSUE THREAD

**Issue by gderoeck** [VeritasSoftware/AspNetCore.Security.Jwt#1]
When applying AzureAD authentication, running the service throws the error below.  It would seem the system is looking for an item in the Configuration file that is missing, but I can't find anything related to that.  Any ideas?  Thank you.

![image](https://user-images.githubusercontent.com/8105483/49456336-290ab700-f7a6-11e8-8f5f-cd7da2abb85d.png)

**Comment by VeritasSoftware** [comment]
I am unable to reproduce the issue.

Only thing I can think of is that the **AzureADSecuritySettings** section of the appsettings is not there.
Or the app cannot find the appsettings.json.

Below is what the SecuritySettings section of appsettings.json should look like.

```
{
  .
  .
  "SecuritySettings": {
    "Secret": "a secret that needs to be at least 16 characters long",
    "Issuer": "your app",
    "Audience": "the client of your app",
    "IdType": "Name",
    "TokenExpiryInHours": 1.2,
    "AppId": "your facebook app id",
    "AppSecret": "your facebook app secret",
    "AzureADSecuritySettings": {
      "AADInstance": "https://login.windows.net/{0}",
      "Tenant": "<B2BADTenant>.onmicrosoft.com",
      "ResourceId": "https://<B2BADTenant>.onmicrosoft.com/<azureappname>",
      "ClientId": "<client-id-web-add>",
      "ClientSecret": "<client-secret>",
      "APIKey": "your endpoint api key here"
    },
    "GoogleSecuritySettings": {
      "ClientId": "<client id>",
      "ClientSecret": "<client secret>",
      "RedirectUri": "http://localhost:59039/",
      "APIKey": "your endpoint api key here"
    }
  }
  .
  .
}
```

**Comment by VeritasSoftware** [comment]
I guess you resolved your issue. Closing issue. Cheers.
