### ISSUE TITLE
Any luck on DotNetCore 3.0/3.1

### ISSUE THREAD

**Issue by jasenf** [VeritasSoftware/AspNetCore.Security.Jwt#10]
Has anyone had any luck reconfiguring the project to work with dotnetcore 3.0 or 3.1?

I'm close but have been getting the following Build-Time warning:
Severity	Code	Description	Project	File	Line	Suppression State
Warning	AD0001	Analyzer 'Microsoft.AspNetCore.Mvc.Analyzers.TopLevelParameterNameAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.	AspNetCore.Security.Jwt	C:\src\dotnet-libraries\AspNetCore.Security.Jwt\AspNetCore.Security.Jwt\CSC	1	Active

**Comment by VeritasSoftware** [comment]
That is not an error thrown by the project. 
Something to do with your Analyzers.

**Comment by jasenf** [comment]
If I grab the latest git release, change target to dotnet 3.0 and compile, these warnings show up.   Not sure i what you mean by ‘my’ analyzers, but I don’t think this is a local issue?

**Comment by VeritasSoftware** [comment]
.Net Core 3 projects have Analyzers. They are under Dependencies. 
Warning can be ignored.

**Comment by VeritasSoftware** [comment]
Closing issue.
