### ISSUE TITLE
Incompatible with latest version of Swagger.

### ISSUE THREAD

**Issue by jasenf** [VeritasSoftware/AspNetCore.Security.Jwt#5]
I don't think this issue should be closed.  It prevents us from using the latest version of Swagger.

_Originally posted by @jasenf in https://github.com/VeritasSoftware/AspNetCore.Security.Jwt/issues/3#issuecomment-486882665_

**Comment by VeritasSoftware** [comment]
I have built the package with Swagger version 3.0.0. 

The higher version of Swagger should work with this but it is not happening. Missing Method exception is thrown. Swagger has not ensured backward compatibility with previous versions.

I am working on the issue.

I will put a new version of my package out soon which will be compatible with the latest Swagger version.

I will keep you updated.

**Comment by jasenf** [comment]
Thank you for this, I appreciate it.

However, it doesn't work.  You've added OpenId code in there that, even when adding Microsoft.OpenId Nuget package still doesn't work.

Also, now that I have your project loaded I see pretty much all the Nuget packages are all out of date.  Hopefully we can just get a refresh on this project, as it would be very helpful!  Thank you!

**Comment by VeritasSoftware** [comment]
I have updated the package to use Swagger version (5.0.0-rc2).

For now, you can clone the source code, update the Swagger reference and replace code file SwaggerExtensions.cs with the attached file.

[SwaggerExtensions.zip](https://github.com/VeritasSoftware/AspNetCore.Security.Jwt/files/3122791/SwaggerExtensions.zip)

These changes will be available in the next Nuget release of the package.

**Comment by VeritasSoftware** [comment]
I have now checked in the changes for using Swagger version (5.0.0-rc2).

Just clone the repo and you will be able to use this Swagger version.

**Comment by jasenf** [comment]
Thank you!

However, now that you convinced me to pull in the source code, I've already had to make a bunch of "enhancements" (ie support for refresh tokens, etc).

Appreciate the quick turnaround on this!

jasen

**Comment by VeritasSoftware** [comment]
You are welcome jasen.

The updated package will be released on Nuget soon.

Please close the issue if all is good.

**Comment by jasenf** [comment]
Hi again --

you upgrades your Swagger packages and code base to a release candidate.  Basically making this project (and the new Swagger code you checked in) completely incompatible with every other library or application that attempts to use Swagger.  Can I ask/recommend that you downgrade all the beta/release candidate packages to only what is in production?  I don't feel in general its a good practice to reference beta code in a library unless it's necessary.   I may have missed it, but I'm not seeing any code you changed that requires Swagger's RC package.

**Comment by VeritasSoftware** [comment]
I have upgraded the package to use the latest Swagger release as you wanted.

I will upgrading it again as and when Swagger is updated.
