### ISSUE TITLE
how to group endpoints

### ISSUE THREAD

**Issue by jfaquinojr** [VeritasSoftware/AspNetCore.Security.Jwt#6]
I wanted to group facebook, twitter, etc under a single endpoint so my swagger looks something like this

/authentication/facebook
/authentication/twitter
/authentication/google

Can I do something like that in the current version or the future?

Thanks!

**Comment by VeritasSoftware** [comment]
I have these route endpoints on different controllers so that they can be turned on/off.
That makes it more configurable.
So, I will not be changing that.

However, you can take the source code and do that for your own personal use, if you want.
