### ISSUE TITLE
[Question] When and How To Add A Custom Claim

### ISSUE THREAD

**Issue by jfaquinojr** [VeritasSoftware/AspNetCore.Security.Jwt#8]
I want to pull data from a database. So my question is:
## Am I doing it right?

```C#
public void ConfigureServices(IServiceCollection services) {
            services.AddSecurity<YayabelsAuthenticator, YayaUser>(this.Configuration, builder =>
            {
                var connectionString = Configuration.GetConnectionString("YayaBase");
                builder.AddClaim("MemberId", u =>
                {
                    using var db = new LiteRepository(connectionString);
                    var member = db.Query<MemberModel>("Members")
                        .Where(m => u.Username == u.Username)
                        .FirstOrDefault();
                    return member?.Id ?? "";
                });
            }, true);
}
```

## What if I want to add many multiple Claims?
I don't want to repeat the db access code for each Claim I add.

**Comment by VeritasSoftware** [comment]
See if you can do this.

Create a static class (eg ClaimsRepository).
Create a static method (eg. string GetMemberId(string connectionStr, string userName) ).

Then, you can call it like:

```
public void ConfigureServices(IServiceCollection services) {
            services.AddSecurity<YayabelsAuthenticator, YayaUser>(this.Configuration, builder =>
            {
                var connectionString = Configuration.GetConnectionString("YayaBase");
                builder.AddClaim("MemberId", u => ClaimsRepository.GetMemberId(connectionString, u.Username));
            }, true);
}
```

**Comment by VeritasSoftware** [comment]
Closing the issue.

**Comment by jfaquinojr** [comment]
> ```
> public void ConfigureServices(IServiceCollection services) {
>             services.AddSecurity<YayabelsAuthenticator, YayaUser>(this.Configuration, builder =>
>             {
>                 var connectionString = Configuration.GetConnectionString("YayaBase");
>                 builder.AddClaim("MemberId", u => ClaimsRepository.GetMemberId(connectionString, u.Username));
>             }, true);
> }
> ```

I assume ClaimsRepository.GetMemberId still pulls data from DB.

I was thinking along the lines of get the user from the DB once, and then add as much Claims I need.
